hotbox-apply-feature: Accept full path to feature script to apply

diff --git a/hotbox-apply-feature b/hotbox-apply-feature
--- a/hotbox-apply-feature
+++ b/hotbox-apply-feature
@@ -32,12 +32,38 @@ test $# -eq 0 || die "Unexpected argument '$1'"
 
 
 #
+# Parse <feature> argument
+#
+feature_file="${feature##*/}"
+feature_dir="${feature%"$feature_file"}"
+feature_dir="${feature_dir%/}"
+case "$feature_file" in
+    *.user.feature.sh)
+        feature_name="${feature_file%.user.feature.sh}"
+        ;;
+    *.system.feature.sh)
+        feature_name="${feature_file%.system.feature.sh}"
+        system=true
+        ;;
+    *.run.feature.sh)
+        die "Can't apply a .run.feature.sh script"
+        ;;
+    *.sh)
+        die "Unrecognised feature script '$feature_file'"
+        ;;
+    *)
+        feature_name="$feature_file"
+        ;;
+esac
+
+
+#
 # User check
 #
 if $system ; then
     test "$(current_user)" = "root" || die "Must be root to set up system features"
 else
-    test "$(current_user)" != "root" || die "Must be unprivileged user to set up features"
+    test "$(current_user)" != "root" || die "Must be unprivileged user to set up user features"
 fi
 
 
@@ -45,10 +71,10 @@ fi
 # Work out command to run
 #
 command="user"
-description="$feature"
+description="$feature_name"
 if $system ; then
     command="system"
-    description="system $feature"
+    description="system $feature_name"
 fi
 
 
@@ -56,7 +82,7 @@ fi
 # Run it
 #
 features=${HOTBOX_SOURCES:-$HOTBOX/features}
-$HOTBOX/lib/feature-exists $features $feature || die "Feature $feature doesn't exist"
-$HOTBOX/lib/feature-command-exists $features $feature $command || exit 0
+$HOTBOX/lib/feature-exists $features $feature_name || die "Feature $feature_name doesn't exist"
+$HOTBOX/lib/feature-command-exists $features $feature_name $command || exit 0
 heading "Setting up $description"
-$HOTBOX/lib/run-feature-command $features $feature $command
+$HOTBOX/lib/run-feature-command $features $feature_name $command
