Try to make feature/spec path handling a little tidier

diff --git a/hotbox-setup-feature b/hotbox-setup-feature
--- a/hotbox-setup-feature
+++ b/hotbox-setup-feature
@@ -34,23 +34,23 @@ test $# -eq 0 || die "Unexpected argument '$1'"
 #
 # Find script
 #
-scriptdir="$($HOTBOX/lib/find-feature-dir $feature)"
-test -n "$scriptdir" || die "Feature $feature not found"
-scriptname="$feature.feature.sh"
-description="$feature"
+feature_dir="$($HOTBOX/lib/find-feature $feature)"
+test -n "$feature_dir" || die "Feature $feature not found"
+feature_script_name="$feature.feature.sh"
+feature_description="$feature"
 
 if $system ; then
     test "$(current_user)" = "root" || die "Must be root to set up system features"
-    description="system $feature"
-    scriptname="$feature.feature.sys.sh"
+    feature_description="system $feature"
+    feature_script_name="$feature.feature.sys.sh"
 fi
 
-script="$scriptdir/$scriptname"
-test -f $script || exit 0
+feature_script="$feature_dir/$feature_script_name"
+test -f $feature_script || exit 0
 
 
 #
 # Run script
 #
-heading "Setting up $description"
-env HOTBOX=$HOTBOX /bin/sh -eu $script
+heading "Setting up $feature_description"
+env HOTBOX=$HOTBOX /bin/sh -eu $feature_script
