Export HOTBOX_TARGET machine or container to specs
So they can adapt themselves to either target environment.

diff --git a/lib/read-spec b/lib/read-spec
--- a/lib/read-spec
+++ b/lib/read-spec
@@ -8,19 +8,29 @@ HOTBOX=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd -P)
 
 location="${1:?expected <location>}"
 spec="${2:?expected <spec>}"
-selected_key="${3:-}"
+target="${3:?expected <target>}"
+selected_key="${4:-}"
 
 
 script="$location/$spec.spec.sh"
 test -f $script || die "Spec $spec not found"
 
+case $target in
+    machine)
+        ;;
+    container)
+        ;;
+    *)
+        die "Unrecognized <target> '$target'"
+esac
 
-env HOTBOX=$HOTBOX /bin/sh -eu $script | while read -r line ; do
+
+env HOTBOX=$HOTBOX HOTBOX_TARGET=$target /bin/sh -eu $script | while read -r line ; do
     key="${line%%:*}"
     value="${line#*:}"
 
     if [ "$key" = "include" ] ; then
-        $HOTBOX/lib/read-spec $location $value $selected_key || die "Error reading included $value spec"
+        $HOTBOX/lib/read-spec $location $value $target $selected_key || die "Error reading included $value spec"
         continue
     fi
 
