Establish container- naming convention for container-only features
- Add --container switch to hotbox-apply-spec

- Get rid of HOTBOX_TARGET and conditionals in specs

diff --git a/lib/read-spec b/lib/read-spec
--- a/lib/read-spec
+++ b/lib/read-spec
@@ -8,28 +8,17 @@ HOTBOX=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd -P)
 
 
 spec="${1:?expected <spec>}"
-target="${2:?expected <target>}"
-selected_key="${3:-}"
+selected_key="${2:-}"
 
 script="$HOTBOX_SOURCES/$spec.spec.sh"
 [ -f "$script" ] || die "Spec $spec not found"
 
-case $target in
-    machine)
-        ;;
-    container)
-        ;;
-    *)
-        die "Unrecognized <target>: $target"
-esac
-
-
-env HOTBOX="$HOTBOX" HOTBOX_TARGET="$target" /bin/sh -eu "$script" | while read -r line ; do
+env HOTBOX="$HOTBOX" /bin/sh -eu "$script" | while read -r line ; do
     key="${line%%:*}"
     value="${line#*:}"
 
     if [ "$key" = "include" ] ; then
-        "$HOTBOX/lib/read-spec" "$value" "$target" "$selected_key" || die "Error reading included $value spec"
+        "$HOTBOX/lib/read-spec" "$value" "$selected_key" || die "Error reading included $value spec"
         continue
     fi
 
